platform :ios, '7.0'

source 'https://github.com/yanghl/seanspec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'commonLib_Example' do
pod 'commonLib', :path => '../'

target 'commonLib_Tests' do
    end
end
