platform :ios, '7.0'

source 'https://github.com/yanghl/seanspec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'commonLib_Example', :exclusive => true do
pod 'commonLib', :path => '../'
pod 'WebViewJavascriptBridge', '~> 5.0.5'

    target 'commonLib_Tests' do
    end
end

