use_frameworks!

target 'commonLib_Example' do
  pod 'commonLib', :path => '../'

  target 'commonLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
